version: '3'
services:
  website:
    container_name: website
    build:
      context: ./
      dockerfile: .
    env_file:
      - local.env
    volumes:
      - './src:/app/src'
    ports:
      - '3000:3000'